name: Chain endpoints
on:
  schedule:
    # twice daily (mornings/afternoons, the latter being busy)
    # - cron:  '50 0/12 * * *'
    # once daily (early mornings, 02:50 GMT, generally not busy)
    - cron:  '50 2 * * *'
  workflow_dispatch:  # <-- allows manual run

jobs:
  endpoints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '20.19.5'   
        cache: 'yarn'

    - run: corepack enable

    - name: check
      env:
        CI_LOG: 123
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ci:chainEndpoints

    - name: issue
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@e27dddc79c92bc6e4562f268fffa5ed752639abd
      env:
        GITHUB_TOKEN: ${{ secrets.CONFIGS_ENDPOINT_CHECK }}
      with:
        filename: .github/chain-endpoints.md
        update_existing: true
